"""
Context Manager
Integrates Planning and conversation history to uniformly manage Agent context.
"""
from typing import List, Dict, Any, Optional
from src.agents.context.conversation_manager import ConversationManager
from src.function_llm import ConversationSummaryLLM


class ContextManager:
    """
    Context Manager - Simplified version
    Responsibility: Integrate Planning and conversation, build LLM messages.
    """
    
    def __init__(
        self,
        max_messages: int = 40,
        min_messages: int = 10,
        max_tokens: int = 16384,
        enable_summary: bool = False,
        summarizer: Optional[ConversationSummaryLLM] = None,
        system_prompt_template: Optional[str] = None,
    ):
        """
        Args:
            max_messages: Maximum number of messages.
            min_messages: Number of messages to retain after summary.
            max_tokens: Maximum number of tokens.
            enable_summary: Whether to enable summary.
            summarizer: Summary generator.
            system_prompt_template: Custom system prompt template.
        """
        self.conversation = ConversationManager(
            max_messages=max_messages,
            min_messages=min_messages,
            max_tokens=max_tokens,
            enable_summary=enable_summary,
            summarizer=summarizer,
        )
        
        self.current_query: str = ""
        self.current_table_path: str = ""
        self.system_prompt_template = system_prompt_template
        self.query_history: List[str] = []
    
    def init_session(
        self, 
        query: str, 
        table_path: str = "", 
        planning_steps: Optional[List[str]] = None,
        planning_result: Optional[Dict[str, Any]] = None,
        keep_summary: bool = False
    ):
        """
        Initialize session.
        
        Args:
            query: User query.
            table_path: Table path.
            planning_steps: Planning steps.
            planning_result: Planning results generated by LLM.
            keep_summary: Whether to retain historical summary.
        """
        self.current_query = query
        self.current_table_path = table_path

        # Update query history
        if not keep_summary:
            self.query_history = []
        self.query_history.append(query)
        # Initialize conversation
        self.conversation.clear(keep_summary=keep_summary)
        self.conversation.set_question(query)
        self.conversation.add_message("user", query)
    
    def update_for_new_question(
        self, 
        new_query: str, 
        planning_steps: Optional[List[str]] = None,
        planning_result: Optional[Dict[str, Any]] = None,
        keep_summary: bool = True
    ):
        """Update context for a new question (Summary mode: retain summary, reset conversation)."""
        self.current_query = new_query
        if not keep_summary:
            self.query_history = []
        self.query_history.append(new_query)
        self.conversation.reset_for_new_question(new_query, keep_summary=keep_summary)
        self.conversation.add_message("user", new_query)
    
    def continue_with_new_question(
        self, 
        new_query: str, 
        planning_steps: Optional[List[str]] = None,
        planning_result: Optional[Dict[str, Any]] = None
    ):
        """
        Follow-up mode: Retain full conversation history, only reset Planning.
        
        Args:
            new_query: New question.
            planning_steps: Planning steps.
            planning_result: Planning results generated by LLM.
        """
        self.current_query = new_query
        self.query_history.append(new_query)
        # Update Planning info in conversation (but do not clear historical messages).
        self.conversation.set_question(new_query)
        # Add new question to conversation history.
        self.conversation.add_message("user", new_query)
    
    def add_message(self, role: str, content):
        """Add message."""
        self.conversation.add_message(role, content)
    
    def build_messages(self, auto_parse: bool = True, dynamic_mode: bool = False) -> List[Dict[str, str]]:
        """Build message list to send to LLM."""
        messages = [{"role": "system", "content": self._build_system_prompt(auto_parse, dynamic_mode)}]
        messages.extend(self.conversation.get_messages())
        return messages
    
    def _build_system_prompt(self, auto_parse: bool = True, dynamic_mode: bool = False) -> str:
        """Build System Prompt."""
        display_queries = self.query_history[:-1] if (self.query_history and self.query_history[-1] == self.current_query) else self.query_history
        history_str = "\n".join([f"Historical Query {i+1}: {q}" for i, q in enumerate(display_queries)]) if display_queries else "None"

        if self.system_prompt_template:
            return self.system_prompt_template.format(
                query=self.current_query,
                enviroment=self.current_table_path,
                # conversation_history=self.conversation.get_summary() if self.conversation.enable_summary else "None",
                conversation_history=history_str,
            )
        else:
             raise ValueError("System prompt template is not set.")
    
    def mark_step_completed(self, result: Optional[str] = None):
        """Mark current step as completed."""
        pass

    def get_session_summary(self) -> Dict[str, Any]:
        """Get session summary."""
        stats = self.conversation.get_stats()
        return {
            "query": self.current_query,
            "table_path": self.current_table_path,
            **stats
        }
    
    def clear(self, keep_summary: bool = False):
        """Clear all context."""
        self.conversation.clear(keep_summary=keep_summary)
        self.current_query = ""
        self.current_table_path = ""
        if not keep_summary:
            self.query_history = []
    
    def set_summarizer(self, summarizer: ConversationSummaryLLM):
        """Set summary generator."""
        self.conversation.summarizer = summarizer
        self.conversation.enable_summary = True
