from typing import Dict, Any
import time
from src.agents.table_agent import TableAgent
from src.agents.user_agent import UserAgent


class MultiTurnOrchestrator:
    """
    Coordinates multi-turn interaction between UserAgent and TableAgent.
    
    Design Notes:
    1. Each sample is an independent evaluation task (completely isolated via reset_session()).
    2. A sample may contain multi-turn conversations (follow-up questions generated by UserAgent).
    3. When TableAgent is initialized with multi_turn_mode=True:
       - Automatically determines continue_mode (False for the first turn in a sample, True for subsequent turns).
       - Conversation history and trace within a sample will accumulate.
       - Saves the complete trace together when the sample ends.
    4. Environment management (if reset_env=True is enabled):
       - Before sample starts: reset_session() restores the environment of the previous sample.
       - First turn of sample: creates a new environment snapshot.
       - In multi-turn mode: turns within a sample do not restore the environment.
    """
    def __init__(
        self, 
        user_agent: UserAgent, 
        table_agent: TableAgent,
    ):
        self.user_agent = user_agent
        self.table_agent = table_agent
        
    def run_eval(self, sample: Dict[str, Any], output_dir: str) -> Dict[str, Any]:
        """
        Runs evaluation on a single sample.
        
        Execution Flow:
        1. Reset agent state (reset_session) to isolate different samples.
        2. First turn: UserAgent generates initial question, TableAgent answers.
        3. Subsequent turns (if any): UserAgent generates follow-up question based on the answer, TableAgent continues to answer.
        4. Save the complete conversation trace.
        
        Args:
            sample: Data sample, may contain single or multi-turn conversation.
            output_dir: Directory to save traces.
            
        Returns:
            Evaluation result containing all turns' Q&A and traces.
        """
        # Reset agents
        self.user_agent.reset(sample)
        task_id = sample.get("id", f"sample_{int(time.time())}")
        table_path = sample.get("file_path", "")
        print(f"Starting evaluation task: {sample.get('question', '')}...")
        
        try:
            # --- First Turn ---
            question = self.user_agent.generate_question(last_answer=None)
            if not question:
                return {"error": "No question generated"}

            # TableAgent runs the first turn            
            print(f"\n[Turn 1]")
            print(f"User: {question}")        
            start_time = time.time()
            agent_output = self.table_agent.run(query=question, table_path=table_path)
            duration = time.time() - start_time
            answer = agent_output.answer
            print(f"  (Duration: {duration:.2f}s, Steps: {agent_output.total_steps})")
            
            # --- Subsequent Turns ---
            turn_idx = 2
            while not self.user_agent.is_finished():
                question = self.user_agent.generate_question(last_answer=answer)
                if not question:
                    break
                print(f"\n[Turn {turn_idx}]")
                print(f"User: {question}")
                # TableAgent automatically determines continue_mode in multi-turn mode
                start_time = time.time()
                agent_output = self.table_agent.run(query=question, table_path=table_path)
                duration = time.time() - start_time
                answer = agent_output.answer
                print(f"  (Duration: {duration:.2f}s, Steps: {agent_output.total_steps})")
            
            # Save complete session trace for TableAgent (accumulated in multi-turn mode)
            if self.table_agent.multi_turn_mode: # 多轮对话结束保存完整的轨迹
                self.table_agent.save_session_trace(task=sample.get('task', None))
                
            # Construct result (using TableAgent's trace)
            result = {
                "sample_id": task_id,
                "original_sample": sample,
                "full_trace": self.table_agent.conversation_trace  # Complete LLM interaction trace
            }
            return result
        except KeyboardInterrupt:
            print("\n[Interrupt] Termination signal received, cleaning up environment...")
            raise
        finally:
            self.table_agent.reset_session()
